### PR TITLE
fill horz-space when using text in listonly mode

### PR DESCRIPTION
**Pull request by azrafe7**

### CODE REVIEW

**Comment by azrafe7** [comment]
It's hard to see in the diff, but it's just a small addition (it adds `select` to the child elements that get 100% width).

**Comment by fponticelli** [comment]
Thank you a lot for the PR but the change should be made here: https://github.com/fponticelli/sui/blob/master/style/sui.styl

The css is generated from that file and your changes will be lost on the next generation.

**Comment by azrafe7** [comment]
Haha, should have known better... was actually weird to have the css all in one line.

Then I guess it's just a matter of adding `select` around here https://github.com/fponticelli/sui/blob/4c947bcdf14d2c1bcc937c6279df0b9726893064/style/sui.styl#L164-L171

Cannot test it though.

**Comment by fponticelli** [comment]
My stylus build process seems to be broken at the moment. I will look into
it ASAP and add your change.

Il giorno mar 28 apr 2015 alle ore 08:06 Giuseppe Di Mauro <
notifications@github.com> ha scritto:

**Pull request closed without merging**
